name: Deploy

on:
  push:
    branches:
      - main

jobs:
  storybook:
    name: Storybook ➡️ GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run storybook:build
      - uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-build # The folder the action should deploy.
